### PR TITLE
intro tweaks2

### PR DESCRIPTION
**Pull request by Robinlovelace**
- Tweak intro
- Shorten intro
- Explain advantages of getting started with R
- More prose refactoring

### CODE REVIEW

**Comment by Robinlovelace** [comment]
https://github.com/r-tmap/tmap/issues/768 causing the build to fail I think. Happy to wait until it's fixed as it will break the workflows.

**Comment by Robinlovelace** [comment]
Heads-up guys I think this is good to go. Fairly non-controversial and some improvements in there I think. Review pre or post merge welcome, let's hope actions pass!

**Comment by Nowosad** [comment]
Nice improvements @Robinlovelace -- I just made a small cleaning to it (https://github.com/geocompx/geocompr/commit/79416e64c9aee645085075d1935c79bf8b8e953c).

**Comment by Robinlovelace** [comment]
Thanks @Nowosad, I've just taken a look at the changes in https://github.com/geocompx/geocompr/commit/79416e64c9aee645085075d1935c79bf8b8e953c and they are all spot on

**Pull request merged**
