### PR TITLE
Replace dplyr::select with select throughout

### LINKED ISSUE #935: dplyr::select() contains namespace in most uses
As shown here `dplyr::select()` is used more frequently than just `select()`: https://github.com/geocompx/geocompr/search?q=select

It's probably worth completing the job started in https://github.com/geocompx/geocompr/pull/934 for all instances for consistency, now that we're switched away from **raster**.

### PR DESCRIPTION
**Pull request by Robinlovelace**
close #935

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Putting this in as a PR in case there are instances where **dplyr** is not yet loaded. We'll find out for the core parts of the book with CI. This finishes the job started in #934

**Review by Nowosad — APPROVED** [review]

**Comment by Nowosad** [comment]
:+1

**Comment by jannes-m** [comment]
For clarification purposes I used  package prefixes for all functions in chapter 12 but maybe this was not necessary for tidyverse functions. But then we should remove tidyverse prefixes from all functions.

**Comment by Robinlovelace** [comment]
> For clarification purposes I used package prefixes for all functions in chapter 12 but maybe this was not necessary for tidyverse functions. But then we should remove tidyverse prefixes from all functions.

Agreed, will make the code more concise.

**Pull request merged**
